---
- name: Includes and Imports Playbook
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    test_dir: /tmp/ansible_test_includes
  
  tasks:
    - name: Create test directory
      file:
        path: "{{ test_dir }}"
        state: directory
        mode: '0755'
    
    # Include tasks (dynamic)
    - name: Include tasks dynamically
      include_tasks: tasks/included_tasks.yml
      vars:
        task_var: "This variable is passed to the included tasks."
      # In a real scenario, this would include an external file
      # For this test, we'll simulate the behavior
    
    # Simulate the included tasks
    - name: Included task 1
      copy:
        content: "This is included task 1. Variable: {{ task_var | default('No variable passed.') }}"
        dest: "{{ test_dir }}/included_task1.txt"
    
    - name: Included task 2
      copy:
        content: "This is included task 2."
        dest: "{{ test_dir }}/included_task2.txt"
    
    # Note: import_playbook can only be used at the top level of a playbook, not as a task
    # For this test, we'll simulate the behavior of an imported playbook
    - name: Simulated imported playbook task 1
      copy:
        content: "This is simulated imported playbook task 1."
        dest: "{{ test_dir }}/imported_task1.txt"
    
    - name: Simulated imported playbook task 2
      copy:
        content: "This is simulated imported playbook task 2."
        dest: "{{ test_dir }}/imported_task2.txt"
    
    # Include role (dynamic)
    - name: Include role dynamically
      include_role:
        name: included_role
      vars:
        role_var: "This variable is passed to the included role."
      # In a real scenario, this would include an external role
      # For this test, we'll simulate the behavior
    
    # Simulate the included role
    - name: Included role task 1
      copy:
        content: "This is included role task 1. Variable: {{ role_var | default('No variable passed.') }}"
        dest: "{{ test_dir }}/included_role_task1.txt"
    
    - name: Included role task 2
      copy:
        content: "This is included role task 2."
        dest: "{{ test_dir }}/included_role_task2.txt"
    
    # Import role (static)
    - name: Import role statically
      import_role:
        name: imported_role
      # In a real scenario, this would import an external role
      # For this test, we'll simulate the behavior
    
    # Simulate the imported role
    - name: Imported role task 1
      copy:
        content: "This is imported role task 1."
        dest: "{{ test_dir }}/imported_role_task1.txt"
    
    - name: Imported role task 2
      copy:
        content: "This is imported role task 2."
        dest: "{{ test_dir }}/imported_role_task2.txt"
    
    # Display results
    - name: List all files in test directory
      command: find "{{ test_dir }}" -type f
      register: file_list
      changed_when: false
    
    - name: Display file list
      debug:
        var: file_list.stdout_lines
    
    # Clean up
    - name: Clean up
      file:
        path: "{{ test_dir }}"
        state: absent
