---
- name: Create directory playbook
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Create directory
      file:
        path: "{{ test_dir | default('/tmp/qa_test_dir') }}"
        state: directory
        mode: '0755'
      register: dir_creation

    - name: Display directory creation result
      debug:
        var: dir_creation
