---
- name: Install Apache playbook
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install Apache
      package:
        name: "{{ apache_package }}"
        state: present
      vars:
        apache_package: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
      register: apache_install

    - name: Display Apache installation result
      debug:
        var: apache_install

    - name: Start Apache service
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: yes
      vars:
        apache_service: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
      register: apache_service_start

    - name: Display Apache service start result
      debug:
        var: apache_service_start
